
export interface idColaborador {
  idColaborador: number;
}

// Generated by https://quicktype.io

export interface ColaboradorCadastro {
  nome:           string;
  cpf:            string;
  usuario:        string;
  senha:          string;
  confirmarSenha: string;
  idTipoUsuario:  number;
  emails:         Email[];
  telefones:      Telefone[];
}

export interface Email {
  email:       string;
  flPrincipal: boolean;
}

export interface Telefone {
  apelido:     string;
  numero:      string;
  flPrincipal: boolean;
}

